name: codegen
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  
  flutter_gen: ^5.11.0
  easy_localization: ^3.0.8
  firebase_auth: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.10.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.0

flutter_gen:
  assets:
    outputs:
      directory_path_enabled: true

  integrations:
    image: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  assets:
    - assets/images/
    - assets/ui_kit_images/

