name: newsapp
description: "A new Flutter project."

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Util
  go_router: ^14.8.1
  equatable: ^2.0.7
  pin_code_fields: ^8.0.1
  country_list_pick: ^1.0.1+6
  share_plus: ^11.0.0
  url_launcher: ^6.3.2

  # Network
  dio: ^5.8.0
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.4

  # Cache
  shared_preferences: ^2.5.3

  # State Managments
  flutter_mobx: ^2.3.0
  mobx: ^2.5.0


  # Localization
  easy_localization: ^3.0.7+1

  # Modules
  codegen:
    path: module/codegen
  
  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  
  # Core
  lucielle:
    git:
      url: https://github.com/Furkanncm/lucielle_core
      ref: main
  

    
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.10.0
  very_good_analysis: ^7.0.0
  json_serializable: ^6.9.0
  mobx_codegen: ^2.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/country/
    - assets/translations/
